services:
  - type: web
    name: cloud-nodejs
    runtime: node
    region: frankfurt
    branch: main
    repo: https://github.com/julienEcole/blueprintRenderTest.git
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    # envVars:
    #   - key: NODE_ENV
    #     value: production
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    region: frankfurt
    type: postgresql
    databaseName : cloud
    user : cloud
    plan: free
    # envVars:
    #   - key: POSTGRES_DB
    #     value: cloud
    #   - key: POSTGRES_USER
    #     value: cloud
    #   - key: POSTGRES_PASSWORD
    #     value: my_password